# This is a TOML document. Boom.

# listen address
ListenAddress = ":8080"

#home page
HomeUrl = "/"

#static folder : aria2 ==> /aria2
StaticFS = ["aria2","yaaw"]

#BasicAuth
#http://admin:admin321@127.0.0.1:8080/aria2/
#http://guest:guest@127.0.0.1:8080/aria2/
[Accounts]
#username admin，password admin321,password must be lower case.
admin="admin321"

#guest="guest"
